config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:edit, :update, :show, :index]

  resources :texts do
    resources :iines, only: [:create, :destroy, :index]
    resources :comments, only: [:create, :destroy]
  end

  resources :posts, only: [:new, :create, :edit, :update, :show, :index, :destroy] do
    resources :messages, only: [:index, :create, :destroy, :edit]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
    resources :likes, only: [:create, :destroy, :index, :show]
  end

  root to: "game#top"

  resources :mercaris, only: [:index, :new, :create, :show, :edit]

  resources :game do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4' 
      get 'step5' 
      get 'top' 
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :text

  validates :content, presence: true
end

app/models/iine.rb
class Iine < ApplicationRecord
  belongs_to :text
  belongs_to :user

  validates_uniqueness_of :text_id, scope: :user_id
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :messages
  validates :text, presence: true
  validates :text, uniqueness: true
  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      '投稿がありません。'
    end
  end
end

app/models/text.rb
class Text < ApplicationRecord
  belongs_to :user
  has_many :iines, dependent: :destroy
  has_many :iined_users, through: :iines, source: :user, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validates :text, uniqueness: true
  validates :text, presence: true
  validates :text,
    length: { minimum: 7, maximum: 22 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  
  has_many :texts, dependent: :destroy
  has_many :iines, dependent: :destroy
  has_many :iined_texts, through: :iines, source: :text

  has_many :messages, dependent: :destroy
  has_many :comments, dependent: :destroy


  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def already_iined?(text)
    self.iines.exists?(text_id: text.id)
  end

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    @post = Post.find(params[:post_id]) 
    @messages = @post.messages.includes(:user).where('id > ?', params[:last_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user! #ログインしてない場合ログイン画面に移動
  before_action :configure_permitted_parameters, if: :devise_controller? 

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) #ユーザー登録時に名前も登録できるようにする
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end

  end

  def destroy
    @comment = Comment.find_by(id: params[:id],text_id: params[:text_id])
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, text_id: params[:text_id])
  end

end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def step1
  end

  def step2
    @all_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))
  end

  def step3
    @all_ranks = Text.find(Iine.group(:text_id).order('count(text_id) desc').limit(5).pluck(:text_id))
  end

  def step4
    @posts = Post.all.order(:id).page(params[:page]).per(5)
  end

  def step5
    @texts = Text.all.order(:id).page(params[:page]).per(5)
  end

  def top
  end

end

app/controllers/iines_controller.rb
class IinesController < ApplicationController
  def index

  end
  
  def create
    @iine = current_user.iines.create(text_id: params[:text_id])
    redirect_back(fallback_location: texts_path)
  end

  def destroy
    @iine = Iine.find_by(text_id: params[:text_id], user_id: current_user.id)
    @iine.destroy
    redirect_back(fallback_location: texts_path)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    
  end
  
  def show
  end

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_post

  def index
    @message = Message.new
    @messages = @post.messages.includes(:user)
  end

  def create
    @message = @post.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to "post_messages_path(params[:message_id])" }
        format.json
      end
    else
      @messages = @post.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(5)
    #@all_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    @like = Like.new
  end

  def new 
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @like = Like.new
  end

  def create
    Post.create(post_params)
    redirect_to posts_path
  end

  def edit
    @all_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))
  end



  private
  def post_params
    params.require(:post).permit(:text).merge(user_id: current_user.id)
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def index
    @texts = Text.all.order(id: "DESC").page(params[:page]).per(5)
    @iine = Iine.new
  end

  def new
    @text = Text.new
    
  end

  def show
    @text = Text.find(params[:id])
    @iine = Iine.new
    @comments = @text.comments
    @comment = Comment.new
  end

  def create
    Text.create(text_params)
    redirect_to texts_path(current_user)
  end

  def edit
    @text = Text.find_by(id: params[:id])
  end
  def update
    # binding.pry
    @text = Text.find_by(id: params[:id])
    @text.update(text_params)
    redirect_to text_path(id: @text.id)
  end

  def destroy
    @text = Text.find_by(id: params[:id], user_id: current_user.id)
    @text.destroy
    flash.now[:alert] = "投稿を削除しました"
    redirect_to texts_path
  end

  private
  def text_params
    params.require(:text).permit(:text).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end
  
  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/game/step1.html.haml
.wrapper
  = render "posts/head"
  = render "posts/foot"
  
#quiz
  %section#container
    %p#question
    #choices
    #btn.disabled Next
  %section#result.hidden
    %p
    %a{:href => ""} Replay?
  :javascript
    'use strict';
    
    {
      const question = document.getElementById('question');
      const choices = document.getElementById('choices');
      const btn = document.getElementById('btn');
      const result = document.getElementById('result');
      const scoreLabel = document.querySelector('#result > p');
    
      const quizSet = shuffle([
        {q: '五・七・五・七・七の音で構成されるものは？' , c: ['短歌', '川柳', '俳句']},
        {q: '俳句には必用だが川柳になくてもいいものは？' , c: ['季語', '口語', '字余り']},
        {q: '川柳が生まれた時代は？' , c: ['江戸時代', '平安時代', '飛鳥時代']},
      ]);
      let currentNum = 0;
      let isAnswered;
      let score = 0;
    
      
    
      function shuffle(arr) {
        for (let i = arr.length - 1; i > 0; i--) {
          const j = Math.floor(Math.random() * (i + 1));
          [arr[j], arr[i]] = [arr[i], arr[j]];
        }
        return arr;
      }
    
      function checkAnswer(li) {
        if (isAnswered ===true) {
          return;
        }
        isAnswered = true;
        if (li.textContent === quizSet[currentNum].c[0]) {
          li.classList.add('correct');
          score++;
        } else {
          li.classList.add('wrong');
        }
    
        btn.classList.remove('disabled');
      }
    
      function setQuiz() {
        isAnswered = false;
    
        question.textContent = quizSet[currentNum].q;
    
        while (choices.firstChild) {
          choices.removeChild(choices.firstChild);
        }
    
        const shuffledChoices = shuffle([...quizSet[currentNum].c]);
        console.log(quizSet[currentNum].c);
        shuffledChoices.forEach(choice => {
          const li = document.createElement('li');
          li.textContent = choice;
          li.addEventListener('click', () => {
            checkAnswer(li);
          });
          choices.appendChild(li);
        });
    
        if (currentNum === quizSet.length - 1) {
          btn.textContent = 'Show Score';
        }
      }
    
      setQuiz();
    
      btn.addEventListener('click', () => {
        if (btn.classList.contains('disabled')) {
          return;
        }
        btn.classList.add('disabled'); 
    
        if (currentNum === quizSet.length - 1) {
          //console.log(`Score: ${score} / ${quizSet.length}`);
          scoreLabel.textContent =`Score: ${score} / ${quizSet.length}`;
          result.classList.remove('hidden');
        } else {
          currentNum++;
          setQuiz();
        }
      });
    }
.footer
  .foot
    %a.face{:href => "https://www.facebook.com/", :target => "”_blank”"}
      %i.fab.fa-facebook-square
    %a.twitter{:href => "https://twitter.com/", :target => "”_blank”"}
      %i.fab.fa-twitter-square
    %a.insta{:href => "https://www.instagram.com/", :target => "”_blank”"}
      %i.fab.fa-instagram

app/views/game/step2.html.haml
.wrapper
  = render "/posts/head"
  = render "/posts/foot"

.back
  .main
    .maintitle
      川柳チャット
      %br
      いいねランキング
      - @all_ranks.each.with_index(1) do |post, i|
        .contents
          .content
            第 
            = i
            位 
            %br 
            = post.text
          .post-message
            = post.show_last_message
          .date
            = post.created_at  
          .comment
            = link_to "川柳チャットする", post_messages_path(post),class: "link2"
          .text  
            = link_to "いいね数", post_path(post),class: "link2"
            = post.liked_users.count
      

app/views/game/step3.html.haml
.wrapper
  = render "posts/head"
  = render "posts/foot"

.today
  .today__title
    みんなの川柳
    %br
    いいねランキング
  .today__senryu
    - if user_signed_in?
      = link_to "川柳を投稿", new_text_path(current_user), class: 'btn5'
  .today__text
    - @all_ranks.each.with_index(1) do |text, i|
      .contents
        .content
          第 
          = i
          位 
          %br 
          = text.text
        - if user_signed_in?
          .syosai
            = link_to "詳細", text_path(text),class: "link1"
            -if text.user_id == current_user.id
              = link_to "編集", edit_text_path(text),class: "link1"
              = link_to text_path(text), method: :delete, data: { confirm: '本当に削除しますか？' },class: "link1" do
                %i.fas.fa-trash-alt
        -else
          .syosai
            = link_to "詳細", new_user_session_path
        .date
          = text.created_at  
        .iinecount
          いいね数：
          = text.iined_users.count

app/views/game/step4.html.haml
.wrapper
  = render "posts/head"
  = render "posts/foot"

.main
  .maintitle
    川柳チャット
    %br
    古い順
    /- @all_ranks.each do |post|
    - @posts.each do |post|
      .contents
        .content 
          = post.text
        .post-message
          = post.show_last_message
        .date
          = post.created_at  
        .comment
          = link_to "川柳チャットする", post_messages_path(post),class: "link2"
        .text  
          = link_to "いいね数", post_path(post),class: "link2"
          = post.liked_users.count
    .page
      = paginate(@posts)

app/views/game/step5.html.haml
.wrapper
  = render "/posts/head"
  = render "/posts/foot"
  
.today
  .today__title
    みんなの川柳
    %br
    古い順
  - if user_signed_in?
    .today__senryu
      = link_to "川柳を投稿", new_text_path(current_user), class: 'btn5'
  .today__text
    - @texts.each do |text|
      .contents
        .content 
          = text.text
        - if user_signed_in?
          .syosai
            = link_to "詳細", text_path(text),class: "link1"
            -if text.user_id == current_user.id
              = link_to "編集", edit_text_path(text),class: "link1"
              = link_to text_path(text), method: :delete, data: { confirm: '本当に削除しますか？' },class: "link1" do
                %i.fas.fa-trash-alt
        -else
          .syosai
            = link_to "詳細", new_user_session_path
            
        .date
          = text.created_at  
        .iinecount
          いいね数：
          = text.iined_users.count
    .page
      = paginate(@texts)

app/views/game/top.html.haml
.wrapper
  = render "posts/head"
  = render "posts/foot"

.slide-wrapper
  %h2.slide-title 川柳縛り
  .change-btn-wrapper
    .change-btn.prev-btn ← 前へ
    .change-btn.next-btn 次へ →
  %ul.slides
    %li.slide.active
      = link_to image_tag("img1.jpg", alt: "サンプル画像",class: "simg"), texts_path
    %li.slide
      = link_to image_tag("img2.jpg", alt: "サンプル画像",class: "simg"), posts_path
    %li.slide
      = link_to image_tag("img3.jpg", alt: "サンプル画像",class: "simg"), step1_game_index_path
  .index-btn-wrapper
    .index-btn みんなの川柳
    .index-btn 川柳チャット
    .index-btn 川柳クイズ

.container19
  .container19-title1
    %i.fab.fa-quora
    川柳縛りとは
  .container19-content
    %ul.accordion1
      %li
        %p.ac1
          %span.blue
            %i.far.fa-question-circle
          川柳縛りとは?
        %ul.inner
          %li.content1-1 川柳投稿サイト。 川柳投稿や川柳チャットができます。 投稿した川柳に「いいね」やコメントをつける事もできランキング順（いいね順）で表示できます。 川柳三択クイズも楽しめます。
      %li
        %p.ac1
          %span.blue
            %i.far.fa-question-circle
          なぜ作ったか？
        %ul.inner
          %li.content1-1 雑誌の応募企画などに、川柳を投稿するのが好きだったので作りました。自分の投稿した川柳が雑誌に掲載された時は嬉しかった事もあり、自分の川柳が評価される機能をつけたいと思い、いいね機能をつけてランキングで表示できる様にしました。 川柳チャットでは川柳に関連したお題を決めてチャットしたら、面白いやりとりができるのではないかと思ったので作りました。 また、川柳をもっと知りたい、学びたいと思う人の為にクイズも作りました。
      %li
        %p.ac1
          %span.blue
            %i.far.fa-question-circle
          川柳チャットとは？
        %ul.inner
          %li.content1-1 チャットのお題を作成するとその中で、お題に関連したチャットをする事ができます。非同期通信と自動更新なのでリアルタイムでチャットができます。LINEや2chの川柳バージョンだと思ってもらえればいいです。ログインすれば使えます。
      %li
        %p.ac1
          %span.blue
            %i.far.fa-question-circle
          みんなの川柳とは？
        %ul.inner
          %li.content1-1 川柳を投稿する事ができます。川柳には「いいね」をつける事ができて、ランキングで表示されます。みんなに「いいね」してもらえるように、センスある川柳をどんどん投稿しましょう。
      %li
        %p.ac1
          %span.blue
            %i.far.fa-question-circle
          川柳クイズとは？
        %ul.inner
          %li.content1-1 川柳についての雑学クイズです。あなたは何問正解できるかな？
      %li
        %p.ac1
          %span.blue
            %i.far.fa-question-circle
          他にどんな機能があるの？
        %ul.inner
          %li.content1-1 ユーザー詳細ページで自分が投稿した川柳や「いいね」した川柳を確認する事ができます。

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Senryublog
    = csrf_meta_tags
    -# = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    -# = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/messages/_head.html.haml
.head
  .title
    川柳縛り  
  .icon
    .icon1
      = link_to edit_user_path(current_user) do
        = current_user.name
    .icon2
      新規登録

.sidehead
  .menu
    .menu1
      お題一覧
    .menu2
      今日の川柳
    .menu3
      ランキング
    .menu4
      川柳チャット

app/views/posts/_foot.html.haml
.footer
  .foot
    =link_to "https://www.facebook.com/", class: "face" do
      <i class="fab fa-facebook-square"></i>
    =link_to "https://twitter.com/", class: "twitter" do
      <i class="fab fa-twitter-square"></i>
    =link_to "https://www.instagram.com/",class: "insta" do
      <i class="fab fa-instagram"></i>

app/views/posts/_head.html.haml
.head
  .title
    = link_to "川柳縛り", root_path, class: 'btn',id: "headtitle"
  .icon
    - if user_signed_in?
      .icon1
        = link_to edit_user_path(current_user), class:"btn" do
          = current_user.name
      .icon1
        = link_to "チャット作成", new_post_path(current_user), class: 'btn'
      .icon1
        = link_to "川柳投稿", new_text_path(current_user), class: 'btn'
      #burger.head__menu.head__bar__box2__text2
        %i.fas.fa-bars
    - else
      .icon1
        = link_to "ログイン", new_user_session_path, class: 'btn'
      .icon1
        = link_to "新規登録", new_user_registration_path, class: 'btn'
      #burger.head__menu.head__bar__box2__text2
        %i.fas.fa-bars

    

-# ドロップダウンメニュー
.sidehead
  %ul.dropdwn
    %li
      川柳チャット
      %ul.dropdwn_menu
        %li
          = link_to "新着順", posts_path, class: 'btn'
        %li
          = link_to "古い順", step4_game_index_path(current_user), class: 'btn'
        %li
          = link_to "ランキング", step2_game_index_path(current_user), class: 'btn'
        - if user_signed_in?
          %li
            = link_to "お題作成", new_post_path(current_user), class: 'btn'
    %li
      みんなの川柳
      %ul.dropdwn_menu
        %li
          = link_to "新着順",texts_path, class: 'btn'
        %li
          = link_to "古い順", step5_game_index_path(current_user), class: 'btn'
        %li
          = link_to "ランキング", step3_game_index_path(current_user), class: 'btn'
        - if user_signed_in?
          %li
            = link_to "川柳投稿", new_text_path(current_user), class: 'btn'
      %li
        ランキング
        %ul.dropdwn_menu
          %li
            = link_to "川柳チャット", step2_game_index_path(current_user), class: 'btn'
          %li
            = link_to "みんなの川柳", step3_game_index_path(current_user), class: 'btn'
      %li
        ゲーム
        %ul.dropdwn_menu
          %li
            = link_to "クイズ",  step1_game_index_path(current_user), class: 'btn'
      - if user_signed_in?
        %li
          = current_user.name
          %ul.dropdwn_menu
            %li
              = link_to "編集", edit_user_path(current_user), class: 'btn'
            %li
              = link_to "詳細", user_path(current_user), class: 'btn'
            %li
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      - else
        %li
          ユーザー登録
          %ul.dropdwn_menu
            %li
              = link_to "ログイン", new_user_session_path, class: 'btn'
            %li
              = link_to "新規登録", new_user_registration_path, class: 'btn'

-# バーガーメニューの内容
.burger
  .burger-menu
    .close2
      %i.fas.fa-times
      閉じる
    .burger-menu__title
      川柳チャット
      .burger-menu__title__list
        = link_to "新着順",texts_path, class: "menulist"
        = link_to "古い順", step5_game_index_path(current_user), class: "menulist"
        = link_to "ランキング", step3_game_index_path(current_user), class: "menulist"
        - if user_signed_in?
          = link_to "チャットお題作成", new_post_path(current_user), class: "menulist"
    .burger-menu__title
      みんなの川柳
      .burger-menu__title__list
        = link_to "新着順",texts_path, class: "menulist"
        = link_to "古い順", step5_game_index_path(current_user), class: "menulist"
        = link_to "ランキング", step3_game_index_path(current_user), class: "menulist"
        - if user_signed_in?
          = link_to "川柳投稿", new_text_path(current_user), class: "menulist"
    .burger-menu__title
      ランキング
      .burger-menu__title__list
        = link_to "川柳チャット", step2_game_index_path(current_user), class: "menulist"
        = link_to "みんなの川柳", step3_game_index_path(current_user), class: "menulist"
    .burger-menu__title
      ゲーム
      .burger-menu__title__list
        = link_to "クイズ",  step1_game_index_path(current_user), class: "menulist"
    .burger-menu__title
      - if user_signed_in?
        = current_user.name
        .burger-menu__title__list
          = link_to "編集", edit_user_path(current_user), class: "menulist"
          = link_to "詳細", user_path(current_user), class: "menulist"
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "menulist"
      - else
        ユーザー登録
        .burger-menu__title__list
          = link_to "ログイン", new_user_session_path, class: "menulist"
          = link_to "新規登録", new_user_registration_path, class: "menulist"

      
    .burger-menu__title
      このサイトについて
    .commentbox
      .commentbox__human
        = image_tag "human.JPG", alt: "Rails icon", id: "pic1", class: "imghuman"
        %p.human-name KASUGA
      .commentbox__box
        .commentbox__box__text
          思いついた川柳を投稿してみよう♪「いいね」がもらえるかも！
          川柳チャットで川柳について語り合えるよ♪
          クイズもあるよ！
    .main__right__tag
      
    .close3
      %i.fas.fa-times
      閉じる

-# トップスクロール
.gotop
  %i.fas.fa-chevron-up

app/views/posts/_main.html.haml
.back
  .main
    .maintitle
      川柳チャット
      %br
      新着順
      /- @all_ranks.each do |post|
      - @posts.each do |post|
        .contents
          .content 
            = post.text
          .post-message
            = post.show_last_message
          .date
            = post.created_at.strftime("%Y/%m/%d %H:%M")
          .comment
            = link_to "川柳チャットする", post_messages_path(post),class: "link2"
          .text  
            = link_to "いいね数", post_path(post),class: "link2"
            = post.liked_users.count
      .page
        = paginate(@posts)

app/views/posts/edit.html.haml
.wrapper
  = render "head"
  = render "foot"


.main
  .maintitle
    川柳チャット
    %br
    いいねランキング
    - @all_ranks.each.with_index(1) do |post, i|
      .contents
        .content
          第 
          = i
          位 
          %br 
          = post.text
        .post-message
          = post.show_last_message
        .date
          = post.created_at  
        .coment
          = link_to "川柳投稿", post_messages_path(post)
        .text  
          = link_to "いいね数", post_path(post)
        .like
          = post.liked_users.count

app/views/posts/show.html.haml
.wrapper
  = render "head"
  = render "foot"

.iine
  - if user_signed_in?
    - if current_user.already_liked?(@post)
      = link_to post_like_path(@post), method: :delete, id: "iine" do
        %i.fas.fa-heart
      #{@post.likes.count}
    - else
      = link_to post_likes_path(@post), method: :post, id: "iine2" do
        %i.far.fa-heart 
      #{@post.likes.count}
  .iineuser 
    いいねしたユーザー
  - @post.liked_users.each do |user|
    = user.name
  .home
    = link_to "ホームへ戻る", posts_path 

app/views/texts/index.html.haml
.wrapper
  = render "posts/head"
  = render "posts/foot"

.today
  .today__title
    みんなの川柳
    %br
    新着順
  - if user_signed_in?
    .today__senryu
      = link_to "川柳を投稿", new_text_path(current_user), class: 'btn5'
  .today__text
    - @texts.each do |text|
      .contents
        .content 
          = text.text
        - if user_signed_in?
          .syosai
            = link_to "詳細", text_path(text),class: "link1"
            -if text.user_id == current_user.id
              = link_to "編集", edit_text_path(text),class: "link1"
              = link_to text_path(text), method: :delete, data: { confirm: '本当に削除しますか？' },class: "link1" do
                %i.fas.fa-trash-alt
              
        -else
          .syosai
            = link_to "詳細", new_user_session_path
        .date
          = text.created_at.strftime("%Y/%m/%d %H:%M")
        .iinecount
          いいね数：
          = text.iined_users.count
    .page
      = paginate(@texts)
        
        



  

app/views/texts/show.html.haml
.wrapper
  = render "posts/head"
  = render "posts/foot"


.today-show
  .today-show__title
    みんなの川柳投稿詳細ページ
  .today-show__text
    = @text.text
  .today-show__user
    = @text.user.name
  .today-show__count
    - if user_signed_in?
      - if current_user.already_iined?(@text)
        = link_to text_iine_path(@text), method: :delete, id: "iine" do
          -# いいね件数: #{@text.iines.count}
          %i.fas.fa-heart  
        #{@text.iines.count}
      - else
        = link_to text_iines_path(@text), method: :post, id: "iine2" do
          %i.far.fa-heart  
        #{@text.iines.count}
  .today-show__iineuser
    いいねしたユーザー:
    - @text.iined_users.each do |user|
      = user.name
  .today-show__comments
    .today-show__comments__title
      コメント一覧
    .today-show__comments__index
      - @comments.each do |c|
        .today-show__comments__index__content
          = c.content
          -if c.user_id == current_user.id
            = link_to text_comment_path(@text, c), method: :delete,class: "link1" do
              %i.fas.fa-trash-alt
        .today-show__comments__index__name
          = c.user.name
    .today-show__comments__form
      - if user_signed_in?
        = form_for [@text, @comment] do |f|
          = f.text_field :content
          %br/
          = f.submit 'コメントする'
  .today-show__destroy
    -if @text.user_id == current_user.id
      = link_to "川柳を削除",text_path(@text),class: "link1", method: :delete, data: { confirm: '本当に削除しますか？' }
      = link_to "川柳を編集", edit_text_path(@text),class: "link1"
  = link_to "みんなの川柳一覧へ戻る", texts_path,class: "link1"